server {
    listen 8080;

    location /DE {
        proxy_pass http://195.85.114.200:80;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }
    location /US {
        proxy_pass http://77.73.238.101:80;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_buffering off;
        proxy_set_header Host $host;
    }
    location /RU {
        proxy_pass http://147.45.79.15:80;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_buffering off;
        proxy_set_header Host $host;
    }

    
    # Optional: Add a default location for other paths, or NGINX will return 404
    location / {
        return 404; # Or serve a default page, or redirect
    }
}
